#!/usr/bin/env python2

import os

from helpers import (read_config, write_config)

CONFIG_PATH = 'config.json'


def create_file(filename):
    if not os.path.exists(filename):
        open(filename, 'a').close()


if __name__ == '__main__':
    try:
        config = read_config(CONFIG_PATH)
    except:
        config = dict()

    config['input'] = [{'driver': 'pygame_input'}]
    config['output'] = [{"driver": "pygame_emulator"}]

    write_config(config, CONFIG_PATH)

    # Phone app will try to connect to a modem.
    # The emulator environment is unlikely to have one
    # In the future, the modem could be emulated.
    # Until then, the app will likely have to be
    # disabled on emulators
    create_file('apps/phone/do_not_load')
    create_file('apps/flashlight/do_not_load')
    create_file('apps/hardware_apps/do_not_load')
